name: quyosh24
description: Quyosh24 - Quyosh paneli yechimlari

publish_to: 'none'

version: 2.0.1+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.0
  http: ^1.1.0
  version: ^2.0.0
  shared_preferences: ^2.2.2
  package_info_plus: ^4.0.0
  connectivity_plus: ^5.0.1
  dio: ^5.3.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/ads/1.jpg
    - assets/images/ads/2.jpg
    - assets/images/ads/3.png
    - assets/images/ads/6.jpg
    - assets/images/ads/7.png
    - assets/images/ads/photo_1_2025-11-06_14-06-18.jpg
    - assets/images/ads/photo_5_2025-11-06_14-06-18.jpg
    - assets/images/ads/photo_6_2025-11-06_14-06-18.jpg
    - assets/images/panels/Longi_550w_copy.jpg
    - assets/images/panels/5a75d156fe23f110123e90ad66a236d8_medium.jpg
    - assets/images/panels/Longi-590-600-watt-solar-panel-high-efficiency-solar-pv-module.jpg
    - assets/images/panels/photo_2025-11-07_21-55-24.jpg
    - assets/images/panels/photo_2025-11-07_21-55-24 (2).jpg
    - assets/images/panels/photo_2025-11-07_21-55-24 (3).jpg
    - assets/images/panels/photo_2025-11-07_21-59-37.jpg
    - assets/images/panels/photo_2025-11-07_22-18-19.jpg
    - assets/images/inverters/34062.jpg
    - assets/images/inverters/goodwe25kw_3c045e2e-2321-4740-a5cd-c4ff7f0e7203.webp
    - assets/images/inverters/inversor-solar-trifasico-goodwe-gw30k-mt.jpg
    - assets/images/inverters/SDTG217-25kW-红色（有屏）-1.png
    - assets/images/inverters/sungrow-wr-front-93a341701c3a51bebed934a797b01891.png
    - assets/images/inverters/sets2_.jpg
    - assets/images/modullar/photo_2025-11-07_21-55-23.jpg
    - assets/images/modullar/photo_2025-11-07_21-55-24.jpg
    - assets/images/modullar/photo_2025-11-07_21-55-25 (2).jpg
    - assets/images/modullar/photo_2025-11-07_21-55-25 (3).jpg
    - assets/images/modullar/photo_2025-11-07_21-55-25.jpg
    - assets/images/modullar/photo_2025-11-07_23-00-32.jpg
    - assets/images/modullar/photo_2025-11-07_23-00-43.jpg
    - public/panels.json

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
